default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  <<: *default
  database: tianosouza_development

test:
  <<: *default
  database: tianosouza_test

production:
  primary: &primary_production
    <<: *default
    database: tianosouza_production
    username: tianosouza
    password: <%= ENV["TIANOSOUZA_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: tianosouza_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tianosouza_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: tianosouza_production_cable
    migrations_paths: db/cable_migrate
